language: php

sudo: false

git:
  depth: 1

services:
    - docker

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: nightly
    fast_finish: true

before_install:
    - docker pull mongo
    - docker run -d --name database -p 27017:27017 mongo
    - docker ps -a
    - pecl install mongo
    - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - if [ "$TRAVIS_PHP_VERSION" != "5.6" ]; then  travis_retry bash -x ./run-tests.sh; fi
  - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then  COVERAGE="--coverage-clover=coverage.xml" travis_retry bash -x ./run-tests.sh; fi

after_success:
- if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml -B $TRAVIS_BRANCH; fi
