version: '2'

services:
    main:
        build: .
        depends_on:
            - mongodb
        links:
            - mongodb
        volumes:
            - ./:/var/www
        environment:
            - DB_MONGODB_HOST=mongodb
        command: journalctl -f
    mongodb:
        image: mongo
